import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'
import { Bell, Camera, CameraOff, Check, History, LogOut, Menu, MessageCircle, Mic, MicOff, MonitorUp, MoreHorizontal, Paperclip, Phone, PhoneOff, Plus, Search, Send, Shield, UserPlus, Users, Video, X } from 'lucide-react'
import { useAuth } from './context/AuthContext'
import { api } from './lib/api'
import { useCallChannel, useRealtime } from './hooks/useRealtime'
import { useWebRTC } from './hooks/useWebRTC'
import type { CallRecord, Conversation, FriendRequest, Message, Notification, User } from './types'

const name = (u?: User) => u?.display_name || u?.username || 'Unknown'
const initials = (value: string) => value.split(/\s+/).map(x => x[0]).join('').slice(0, 2).toUpperCase()

function AuthScreen() {
  const { login, register } = useAuth(); const [mode, setMode] = useState<'login' | 'register'>('login'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setBusy(true); setError(''); const data = new FormData(e.currentTarget); try { if (mode === 'login') await login(String(data.get('email')), String(data.get('password'))); else await register({ username: String(data.get('username')), email: String(data.get('email')), password: String(data.get('password')) }) } catch (err) { setError(err instanceof Error ? err.message : 'Unable to continue') } finally { setBusy(false) } }
  return <main className="auth"><section className="auth-copy"><div className="brand"><span>R</span> RELAY</div><p className="eyebrow">YOUR PEOPLE. IN REAL TIME.</p><h1>Conversation<br/>without the <i>noise.</i></h1><p>Messages, calls, and shared moments in one focused place.</p><div className="signal"><span/><span/><span/><span/></div></section><section className="auth-card"><div><p className="eyebrow">WELCOME {mode === 'login' ? 'BACK' : 'IN'}</p><h2>{mode === 'login' ? 'Sign in to Relay' : 'Create your account'}</h2></div><form onSubmit={submit}>{mode === 'register' && <label>Username<input name="username" required minLength={2} autoComplete="username"/></label>}<label>Email<input name="email" required type="email" autoComplete="email"/></label><label>Password<input name="password" required type="password" minLength={8} autoComplete={mode === 'login' ? 'current-password' : 'new-password'}/></label>{error && <p className="error" role="alert">{error}</p>}<button className="primary" disabled={busy}>{busy ? 'Connecting…' : mode === 'login' ? 'Enter Relay' : 'Join Relay'}</button></form><button className="text-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New here? Create an account' : 'Already a member? Sign in'}</button></section></main>
}

type Panel = 'chat' | 'friends' | 'requests' | 'notifications' | 'calls'
export default function App() {
  const { user, loading, logout } = useAuth(); const [conversations, setConversations] = useState<Conversation[]>([]); const [selected, setSelected] = useState<string | null>(null); const [messages, setMessages] = useState<Message[]>([]); const [friends, setFriends] = useState<User[]>([]); const [requests, setRequests] = useState<FriendRequest[]>([]); const [notifications, setNotifications] = useState<Notification[]>([]); const [calls, setCalls] = useState<CallRecord[]>([]); const [panel, setPanel] = useState<Panel>('chat'); const [error, setError] = useState(''); const [mobileNav, setMobileNav] = useState(false); const [newChat, setNewChat] = useState(false); const [call, setCall] = useState<CallRecord | null>(null)
  const token = localStorage.getItem('relay_token') || ''
  const receiveMessage = useCallback((message: Message) => setMessages(current => current.some(x => x.id === message.id) ? current : [...current, message]), [])
  const receiveNotification = useCallback((notification: Notification) => { setNotifications(current => [notification, ...current]); if (notification.type === 'friend_request_accepted') void api.friends().then(page => setFriends(page.data)) }, [])
  const receiveCall = useCallback((incoming: CallRecord) => setCall(incoming), [])
  const realtime = useRealtime(token, user?.id || '', selected, receiveMessage, receiveNotification, receiveCall)
  const callChannel = useCallChannel(realtime.socket, call?.id || null)
  const finishCall = useCallback(() => { if (call && call.initiator.id === user?.id) void api.endCall(call.id); setCall(null) }, [call, user?.id])
  const rtc = useWebRTC(callChannel, call?.kind === 'video', call?.initiator.id === user?.id, finishCall)
  useEffect(() => {
    if (!call || call.initiator.id === user?.id || rtc.localStream) return
    const context = new AudioContext()
    const ring = () => {
      const startedAt = context.currentTime
      for (const [frequency, delay] of [[660, 0], [880, 0.22]] as const) {
        const oscillator = context.createOscillator(), gain = context.createGain()
        oscillator.frequency.value = frequency; gain.gain.setValueAtTime(0, startedAt + delay); gain.gain.linearRampToValueAtTime(0.16, startedAt + delay + 0.02); gain.gain.linearRampToValueAtTime(0, startedAt + delay + 0.18)
        oscillator.connect(gain).connect(context.destination); oscillator.start(startedAt + delay); oscillator.stop(startedAt + delay + 0.2)
      }
    }
    void context.resume().then(ring)
    const timer = window.setInterval(ring, 1600)
    return () => { window.clearInterval(timer); void context.close() }
  }, [call, rtc.localStream, user?.id])
  const current = conversations.find(c => c.id === selected)
  const loadAll = useCallback(async () => { try { const [c, f, r, n] = await Promise.all([api.conversations(), api.friends(), api.friendRequests(), api.notifications()]); const conversationId = selected || c.data[0]?.id; const h = conversationId ? await api.calls(conversationId) : { data: [] }; setConversations(c.data); setSelected(value => value || c.data[0]?.id || null); setFriends(f.data); setRequests(r.data); setNotifications(n.data); setCalls(h.data) } catch (e) { setError(e instanceof Error ? e.message : 'Could not load workspace') } }, [selected])
  useEffect(() => { if (user) void loadAll() }, [user, loadAll])
  useEffect(() => { if (selected) api.messages(selected).then(page => setMessages(page.data)).catch(e => setError(e.message)) }, [selected])
  if (loading) return <div className="splash"><div className="logo-mark">R</div><p>Opening Relay…</p></div>
  if (!user) return <AuthScreen />
  const openPanel = (value: Panel) => { setPanel(value); setMobileNav(false); if (value === 'friends') void api.friends().then(page => setFriends(page.data)).catch(e => setError(e.message)) }
  const startChat = async (memberIds: string[], groupName?: string) => { try { const conversation = await api.createConversation(memberIds, groupName); setConversations(current => [conversation, ...current.filter(item => item.id !== conversation.id)]); setSelected(conversation.id); setPanel('chat'); setMobileNav(false); setNewChat(false) } catch (e) { setError((e as Error).message) } }
  const beginCall = async (kind: 'voice' | 'video') => { if (!selected) return; try { const record = await api.createCall(selected, kind); setCall(record) } catch (e) { setError((e as Error).message) } }
  return <div className="app">
    <aside className={`rail ${mobileNav ? 'open' : ''}`}><div className="logo-mark">R</div><nav aria-label="Primary"><button className={panel === 'chat' ? 'active' : ''} onClick={() => openPanel('chat')} aria-label="Chats"><MessageCircle/></button><button className={panel === 'friends' ? 'active' : ''} onClick={() => openPanel('friends')} aria-label="Friends"><Users/></button><button className={panel === 'requests' ? 'active' : ''} onClick={() => openPanel('requests')} aria-label="Friend requests"><UserPlus/></button><button className={panel === 'notifications' ? 'active' : ''} onClick={() => openPanel('notifications')} aria-label="Notifications"><Bell/>{notifications.some(n => !n.read_at) && <b/>}</button><button className={panel === 'calls' ? 'active' : ''} onClick={() => openPanel('calls')} aria-label="Call history"><History/></button></nav><button onClick={() => void logout()} aria-label="Sign out"><LogOut/></button></aside>
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><header><div><small>WORKSPACE</small><strong>Relay Central</strong></div><button onClick={() => setNewChat(true)} aria-label="New conversation"><Plus/></button></header><label className="search"><Search/><input placeholder="Search conversations" aria-label="Search conversations"/></label><div className="section-title"><span>MESSAGES</span><span>{conversations.length}</span></div><div className="conversation-list">{conversations.map(c => { const title = c.name || c.members.map(m => m.user).filter(m => m.id !== user.id).map(name).join(', ') || 'New conversation'; const online = c.members.some(m => realtime.presence[m.user.id] === 'online'); return <button key={c.id} className={selected === c.id && panel === 'chat' ? 'selected' : ''} onClick={() => { setSelected(c.id); setPanel('chat'); setMobileNav(false) }}><Avatar label={title} online={online}/><span><strong>{title}</strong><small>{`${c.members.length} members`}</small></span></button> })}</div><div className="profile"><Avatar label={name(user)} online/><span><strong>{name(user)}</strong><small>{realtime.connected ? 'Online' : 'Reconnecting…'}</small></span><button aria-label="Profile menu"><MoreHorizontal/></button></div></aside>
    <main className="content"><button className="mobile-menu" onClick={() => setMobileNav(!mobileNav)} aria-label="Open navigation"><Menu/></button>{error && <div className="toast" role="alert">{error}<button onClick={() => setError('')} aria-label="Dismiss"><X/></button></div>}{panel === 'chat' ? <Chat conversation={current} messages={messages} user={user} onSent={receiveMessage} onCall={beginCall} onError={setError}/> : <Dashboard panel={panel} friends={friends} requests={requests} notifications={notifications} calls={calls} onRefresh={loadAll} onError={setError} onStartChat={friend => void startChat([friend.id])}/>}</main>
    {newChat && <NewConversationDialog friends={friends} onClose={() => setNewChat(false)} onCreate={startChat}/>}
    {call && <CallOverlay call={call} channelReady={Boolean(callChannel)} rtc={rtc}/>} {mobileNav && <button className="backdrop" onClick={() => setMobileNav(false)} aria-label="Close navigation"/>}
  </div>
}

function Avatar({ label, online }: { label: string; online?: boolean }) { return <span className="avatar" aria-hidden>{initials(label)}{online && <i/>}</span> }
function Chat({ conversation, messages, user, onSent, onCall, onError }: { conversation?: Conversation; messages: Message[]; user: User; onSent(m: Message): void; onCall(k: 'voice' | 'video'): void; onError(s: string): void }) {
  const [body, setBody] = useState(''), [uploading, setUploading] = useState(false); const file = useRef<HTMLInputElement>(null); const end = useRef<HTMLDivElement>(null); const title = conversation?.name || conversation?.members.map(m => m.user).filter(m => m.id !== user.id).map(name).join(', ') || 'Conversation'
  useEffect(() => end.current?.scrollIntoView({ behavior: 'smooth' }), [messages])
  const send = async (e: FormEvent) => { e.preventDefault(); if (!conversation || !body.trim()) return; try { onSent(await api.sendMessage(conversation.id, body.trim())); setBody('') } catch (err) { onError((err as Error).message) } }
  const upload = async (input?: File) => { if (!input || !conversation) return; setUploading(true); try { onSent(await api.sendMessage(conversation.id, body.trim(), input)); setBody('') } catch (e) { onError((e as Error).message) } finally { setUploading(false) } }
  if (!conversation) return <div className="empty"><MessageCircle/><h2>Start a conversation</h2><p>Create a direct or group chat from the plus button.</p></div>
  return <><header className="chat-head"><div><Avatar label={title}/><span><h2>{title}</h2><small>{conversation.kind === 'group' ? `${conversation.members.length} members` : 'Direct message'}</small></span></div><div><button onClick={() => onCall('voice')} aria-label="Start voice call"><Phone/></button><button onClick={() => onCall('video')} aria-label="Start video call"><Video/></button><button onClick={() => moderate(conversation)} aria-label="Moderation options"><Shield/></button></div></header><section className="messages" aria-live="polite">{messages.map((m, i) => <article key={m.id} className={m.sender.id === user.id ? 'mine' : ''}><Avatar label={name(m.sender)}/><div><p><strong>{name(m.sender)}</strong><time>{new Date(m.inserted_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</time></p>{m.deleted_at ? <em>Message removed</em> : <span>{m.body}{m.attachment && <a href={m.attachment.url} target="_blank" rel="noreferrer">{m.attachment.filename}</a>}</span>}</div>{i === messages.length - 1 && <div ref={end}/>}</article>)}</section><form className="composer" onSubmit={send}><input ref={file} hidden type="file" onChange={e => void upload(e.target.files?.[0])}/><button type="button" onClick={() => file.current?.click()} disabled={uploading} aria-label="Attach file"><Paperclip/></button><input value={body} onChange={e => setBody(e.target.value)} placeholder={`Message ${title}`} aria-label="Message"/><button className="send" disabled={!body.trim() || uploading} aria-label="Send"><Send/></button></form></>
}

function Dashboard({ panel, friends, requests, notifications, calls, onRefresh, onError, onStartChat }: { panel: Panel; friends: User[]; requests: FriendRequest[]; notifications: Notification[]; calls: CallRecord[]; onRefresh(): Promise<void>; onError(s: string): void; onStartChat(user: User): void }) {
  const addFriend = async () => { const username = prompt('Enter their exact username'); if (!username) return; try { await api.requestFriend(username); await onRefresh() } catch (e) { onError((e as Error).message) } }
  const title = { friends: 'Your people', requests: 'Friend requests', notifications: 'Activity', calls: 'Call history', chat: '' }[panel]
  return <section className="dashboard"><header><p className="eyebrow">RELAY / {panel.toUpperCase()}</p><h1>{title}</h1>{panel === 'friends' && <button className="primary compact" onClick={addFriend}><UserPlus/> Add friend</button>}</header><div className="cards">{panel === 'friends' && friends.map(u => <div className="person" key={u.id}><Avatar label={name(u)} online={u.status === 'online'}/><span><strong>{name(u)}</strong><small>@{u.username}</small></span><button onClick={() => onStartChat(u)} aria-label={`Message ${name(u)}`}><MessageCircle/></button></div>)}{panel === 'requests' && requests.map(r => <div className="person" key={r.id}><Avatar label={name(r.sender)}/><span><strong>{name(r.sender)}</strong><small>incoming request</small></span><><button onClick={() => void api.answerFriend(r.id, true).then(onRefresh)} aria-label="Accept"><Check/></button><button onClick={() => void api.answerFriend(r.id, false).then(onRefresh)} aria-label="Reject"><X/></button></></div>)}{panel === 'notifications' && notifications.map(n => <button className={`notice ${n.read_at ? '' : 'unread'}`} key={n.id} onClick={() => void api.readNotification(n.id).then(onRefresh)}><Bell/><span><strong>{n.type.replaceAll('_', ' ')}</strong><small>{JSON.stringify(n.data)}</small></span><time>{new Date(n.inserted_at).toLocaleDateString()}</time></button>)}{panel === 'calls' && calls.map(c => <div className="person" key={c.id}><span className="icon-box">{c.kind === 'video' ? <Video/> : <Phone/>}</span><span><strong>{name(c.initiator)}</strong><small>{c.status} · {new Date(c.started_at || c.inserted_at).toLocaleString()}</small></span></div>)}</div>{((panel === 'friends' && !friends.length) || (panel === 'requests' && !requests.length) || (panel === 'notifications' && !notifications.length) || (panel === 'calls' && !calls.length)) && <div className="empty"><Users/><h2>Nothing here yet</h2><p>This space will update as things happen.</p></div>}</section>
}

function NewConversationDialog({ friends, onClose, onCreate }: { friends: User[]; onClose(): void; onCreate(ids: string[], name?: string): Promise<void> }) {
  const [query, setQuery] = useState(''), [selected, setSelected] = useState<string[]>([]), [groupName, setGroupName] = useState(''), [busy, setBusy] = useState(false)
  const matches = friends.filter(friend => `${name(friend)} ${friend.username}`.toLowerCase().includes(query.toLowerCase()))
  const toggle = (id: string) => setSelected(current => current.includes(id) ? current.filter(item => item !== id) : [...current, id])
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!selected.length) return; setBusy(true); await onCreate(selected, selected.length > 1 ? groupName.trim() || undefined : undefined); setBusy(false) }
  return <div className="dialog-backdrop" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget) onClose() }}><form className="new-chat-dialog" role="dialog" aria-modal="true" aria-labelledby="new-chat-title" onSubmit={submit}><header><div><p className="eyebrow">NEW CONVERSATION</p><h2 id="new-chat-title">Choose your people</h2></div><button type="button" onClick={onClose} aria-label="Close"><X/></button></header><label className="search"><Search/><input autoFocus value={query} onChange={event => setQuery(event.target.value)} placeholder="Search friends" aria-label="Search friends"/></label><div className="friend-picker">{matches.map(friend => <button type="button" className={selected.includes(friend.id) ? 'chosen' : ''} key={friend.id} onClick={() => toggle(friend.id)}><Avatar label={name(friend)} online={friend.status === 'online'}/><span><strong>{name(friend)}</strong><small>@{friend.username}</small></span><i>{selected.includes(friend.id) ? <Check/> : <Plus/>}</i></button>)}{!matches.length && <div className="picker-empty"><Users/><p>{friends.length ? 'No friends match that search.' : 'Add a friend before starting a chat.'}</p></div>}</div>{selected.length > 1 && <label className="group-name">Group name <input value={groupName} onChange={event => setGroupName(event.target.value)} placeholder="Weekend crew"/></label>}<footer><span>{selected.length ? `${selected.length} selected` : 'Select at least one friend'}</span><button className="primary compact" disabled={!selected.length || busy}>{busy ? 'Creating…' : 'Start chat'}</button></footer></form></div>
}

function CallOverlay({ call, channelReady, rtc }: { call: CallRecord; channelReady: boolean; rtc: ReturnType<typeof useWebRTC> }) {
  const localRef = useRef<HTMLVideoElement>(null), remoteRef = useRef<HTMLVideoElement>(null); useEffect(() => { if (localRef.current) localRef.current.srcObject = rtc.localStream; if (remoteRef.current) remoteRef.current.srcObject = rtc.remote }, [rtc.localStream, rtc.remote])
  return <div className="call" role="dialog" aria-modal="true" aria-label={`${call.kind} call`}><div className="call-stage">{rtc.remote ? <video ref={remoteRef} autoPlay playsInline/> : <div className="calling"><Avatar label={name(call.initiator)}/><h2>{channelReady ? 'Ready to connect' : 'Connecting…'}</h2><p>{call.kind} call with {name(call.initiator)}</p>{!rtc.localStream && <button className="primary compact" disabled={!channelReady} onClick={() => void rtc.start()}>Join call</button>}</div>}{rtc.localStream && call.kind === 'video' && <video className="local-video" ref={localRef} autoPlay muted playsInline/>}</div><div className="call-controls"><button className={rtc.muted ? 'off' : ''} onClick={rtc.toggleMute} aria-label={rtc.muted ? 'Unmute' : 'Mute'}>{rtc.muted ? <MicOff/> : <Mic/>}</button>{call.kind === 'video' && <button className={rtc.cameraOff ? 'off' : ''} onClick={rtc.toggleCamera} aria-label={rtc.cameraOff ? 'Turn camera on' : 'Turn camera off'}>{rtc.cameraOff ? <CameraOff/> : <Camera/>}</button>}<button className={rtc.sharing ? 'active' : ''} onClick={() => void rtc.shareScreen()} aria-label="Share screen"><MonitorUp/></button><button className="hangup" onClick={rtc.stop} aria-label="End call"><PhoneOff/></button></div></div>
}

async function moderate(conversation: Conversation) { const user = prompt(`Member username to moderate: ${conversation.members.map(x => x.user.username).join(', ')}`); const member = conversation.members.find(x => x.user.username === user); if (!member) return; const action = prompt('Action: kick or ban') as 'kick' | 'ban' | null; if (action && ['kick', 'ban'].includes(action)) await api.moderate(conversation.id, member.user.id, action) }
